### ISSUE TITLE
User can view a preview of a selected file. 

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/scribe#1]
# Motivation
In-line, we want to be able to view the file. This will allow us to preview it. We'll add options to edit the file later. We can either view a preview of a file system already uploaded to Scribe, or something that is on your system.

# Task implementation
- [x] Set up wireframe
- [x] Set up project scaffolding
- [x] Set up dependencies, both dev and using
- [x] Set up scripts to automate development.
- [x] Use libraries to be able to upload files from the system
- [x] Get around the problem of multiple people multiple files of the same name
- [x] Set up databases to track which file was edited from which.
- [x] Create an overlay for an editor. 
- [x] Dedicate that new editor view to the new file view. 
- [x] On preview, make sure that the spacing looks EXACTLY like it looks like in the file.
- [x] Make sure on every selection of the file it re-renders the page to load the new file's contents. 

# Wireframe

![screen shot 2017-08-07 at 11 02 39 am](https://user-images.githubusercontent.com/26865352/29039386-f4555bf0-7b5f-11e7-94ee-7592cdfd344e.png)
