### ISSUE TITLE
Upload to AWS S3

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/scribe#12]
# Motivation
Our files keep getting destroyed with every deploy and are killed after a while from inactivity. We want to persist these files.

# Task Implementation
- [x] Read up on AWS S3 NPM
- [x] Get the information from my amazon account.
- [x] Hide the processes so that they don't ever grab my access information
- [x] Test out AWS functionality
- [x] Create Routes to get the AWS routing working.
- [x] Fixes routes as necessary. 
- [x] Make sure that the files are actually there in both AWS and scribe.
- [x] Make sure that the files get persisted. 
- [x] Make sure that the permalinks to these files work. 
- [x] Make sure that the table that show these files correctly map to the file on system. 
- [x] Fix the upload menu so that you can see a progress circle while uploading
- [x] Fix the upload menu so that the buttons work on any browser and that the buttons actually work
- [x] Fix the search menu so that every time you get onto it it refreshes the list.
