### ISSUE TITLE
User can delete uploaded files.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/scribe#19]
# Motivation
We want to be able to delete saved files from the system.

# Task implementation
- [x] Make the table selectable again
- [x] Create a button to allow the process of deletion
- [x] Create a route in the server to handle said deletions
- [x] Create a fetch to post the request. 
- [x] Verify that the files were deleted. 
- [x] Verify that the files match the scribe database. 

# Wireframe
![screen shot 2017-08-18 at 11 25 35 am](https://user-images.githubusercontent.com/26865352/29472257-02c4fab4-8408-11e7-8fa9-7713dee2de5b.png)
