### ISSUE TITLE
User can save edited files to scribe.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/scribe#2]
# Motivation
We want to be able to save a file system onto scribe.

# Task implementation
- [x] Create a button to allow saving of the file. 
- [x] Allow user to save the file to a directory of their choosing
- [x] update the database to allow people to see the saved changes.
- [x] make sure that the database data is correctly linked. 
- [x] When loading the edit mode, make sure that the formatting looks EXACTLY like the preview.
- [x] If the user didn't save and tries to reload or close the page while in edit mode, prompt them the option to stay on the page.
- [x] With every saved edit, make sure that the database history is correctly linked. 
- [x] When you exit the editor menu, re-render the table.
- [x] Show loading progress on uploading to scribe.

# Wireframe
![screen shot 2017-08-07 at 11 07 48 am](https://user-images.githubusercontent.com/26865352/29039570-a89cf578-7b60-11e7-88b5-393885053e9f.png)
