### ISSUE TITLE
User can view a history of an editted file.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/scribe#3]
# Motivation
We want to be able to have the user see the history and differences between each save on the system. We also want them to see the differences made between each file. 

# Task implementation
- [ ] Confirm the database history is correct.
- [ ] Create the associations with the history of each.
- [ ] Create a tree-like diagram with each history pullup.
- [ ] Render the tree in a way that the user is interested in seeing the historical differences between each file version. 
- [ ] Allow the user to compare histories and differences of files, side by side. Old on left, new on right.
- [ ] If text was added, make sure that the text appears on a green line on the right.
- [ ] If text was removed, on the left side show a red line to show deleted lines. 

# Wireframe
Coming soon!
