### ISSUE TITLE
User can search for files on the system.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/scribe#4]
# Motivation
Now that we can save the files onto the system and preview files from scribe or our own file system, it is time to let people search for files on scribe.

# Task implementation
- [x] Create a search component for the file search.
- [x] Refactored file-tabs.js file in order to display all the files as a default view.
- [x] Set up a GET request for obtaining a list, based on the search parameters.
- [x] Refactored the GET request and handleFileList method.

# Wireframe
![screen shot 2017-08-14 at 1 12 59 pm](https://user-images.githubusercontent.com/26865352/29289689-5a79714a-80f2-11e7-9689-6e04ae48c32e.png)
