### ISSUE TITLE
User can upload files onto scribe.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/scribe#5]
# Motivation
We want to let users upload files from their system to scribe

# Task implementation
- [x] Create a route to touch files with text
- [x] create a button allow users to select a file from their system
- [x] Allow people to see that the file was uploaded after it is finished processing
- [x] Verify that the file was saved correctly onto the system.
- [x] Be able to via a GET route to correctly pull out the right file. 
- [x] Verify that the file pulled out is the correct one.
- [x] Make the upload menu look good.
# Wireframe
![screen shot 2017-08-08 at 10 23 05 am](https://user-images.githubusercontent.com/26865352/29085256-994f4670-7c23-11e7-937d-a14f61302b79.png)
