### ISSUE TITLE
User can download a file.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/scribe#6]
# Motivation
Now that we can upload a file and preview them, we want to be able to let the user download the files as well. 

# Task implementation
- [x] Create a download button
- [x] On the button click, allow the user to download the file
- [x] Make sure that the file can be saved as the original file name
- [x] Make sure that the file can be seen in the download dialogue
- [x] Make sure that the file can be opened appropriately after downloading

# Wireframe
![screen shot 2017-08-17 at 10 38 57 am](https://user-images.githubusercontent.com/26865352/29425492-4d47ed6a-8338-11e7-8937-6517445ef7fc.png)
