### ISSUE TITLE
User can generate a permalink to a file.

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/scribe#7]
# Motivation
We want to be able to serve in the application, a permalink to the server.

# Task Implementation
- [ ] Figure out react routing
- [ ] Play with it
- [ ] Route to the editor view of the file when you get to the preview.
- [ ] Create a button to save the link to the editor state. 
- [ ] Test it out with the bookmark to the view itself. 
- [ ] Test it many times to ensure its robustness.
