### ISSUE TITLE
User can view a list of uploaded files

### ISSUE THREAD

**Issue by kennykimjr** [kennykimjr/scribe#9]
# Motivation
Even though we can upload files, we want to see that the files are actually on the system. We will do this by looking into the directory, and then finding the files in the list. 

# Task Implementation
- [x] Make sure that you can accurately switch between 2 views, **View and Upload**
- [x] Make sure that the view is refreshed with each switch of the tab. 
- [x] Create a route to peruse through all the files in \uploads
- [x] Check that the files are on the system
- [x] Create routes to verify the contents of the files
- [x] Be able to render a list of the files that actually exist
- [x] Make sure that the files that rendered actually match the files on system. 
- [x] Make sure that the new files are actually on the system. 

# Wireframe
![screen shot 2017-08-10 at 10 00 49 am](https://user-images.githubusercontent.com/26865352/29182196-d22b4652-7db2-11e7-812e-b13a0e0788a6.png)

![screen shot 2017-08-10 at 10 37 46 am](https://user-images.githubusercontent.com/26865352/29183573-0650d7d0-7db8-11e7-8d30-f9cc4f4b1071.png)
